config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  resources :groups, only: [:index, :new, :create, :destroy] do
   resources :transfers, only: [:index, :new, :create, :show, :destroy] 
  end
  # Defines the root path route ("/")
  
  devise_scope :user do
    authenticated :user do
      root "groups#index", as: :authenticated_root
    end
    unauthenticated :user do
      root "home#index", as: :unauthenticated_root
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :transfers

  validates :name, presence: true, length: { maximum: 250 }
  validates :icon, presence: true, length: { maximum: 250 }

  def self.created_by_current_user(current_user)
    where(user_id: current_user.id).order(created_at: :desc)
  end
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :groups

  validates :name, presence: true, length: { maximum: 250 }
  validates :amount, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :full_name, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :transfers, foreign_key: 'author_id'
  has_many :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[full_name email password])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[full_name email password])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = Group.created_by_current_user(current_user)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user
    if @group.save
      redirect_to groups_path, notice: 'Category was successfully created'
    else
      render :new
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :authenticate_user!

  def index
    @transfers = Transfer.joins(:groups).where(groups: { id: params[:group_id] }).order(created_at: :desc)
    @group = Group.find(params[:group_id])
  end

  def new
    @transfer = Transfer.new
    @groups = Group.created_by_current_user(current_user)
  end

  # rubocop:disable Metrics/CyclomaticComplexity
  # rubocop:disable Metrics/PerceivedComplexity
  def create
    if params[:transfer][:group_ids].present? && params[:transfer][:group_ids].all? do |id|
         id.to_i.zero?
       end
      render :new
      return
    end
    params = transfer_params
    @transfer = Transfer.new(name: params[:name], amount: params[:amount])
    @transfer.author = current_user
    @groups_id = params[:group_ids]

    @groups_id.each do |id|
      group = Group.find(id) unless id == '0'
      @transfer.groups.push(group) unless group.nil?
    end

    if @transfer.save
      redirect_to group_transfers_path(@transfer.groups.first.id), notice: 'Transfer added successfully'
    else
      render :new
    end
  end

  # rubocop:enable Metrics/CyclomaticComplexity
  # rubocop:enable Metrics/PerceivedComplexity
  def show
    @transfer = Transfer.find(params[:id])
  end

  def transfer_params
    params.require(:transfer).permit(:name, :amount, group_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.erb
<%= render 'shared/navbar', group: @groups %>
<button class="back"><%= link_to "back", groups_path  %></button>

<div class="group_main_div">
<h2 class="group_main_title">All Category</h2>

<section class="main_group_section">
<div class="groups_section">
  <% @groups.each do |group| %>
    <div>
      <img class="group-image" src="<%= group.icon %>" alt="icon" />
    </div>
    <div class="group_name_div">
      <p><%= link_to group.name, group_transfers_path(group),  class: "group_name" %></p>
    </div>
    <div class="group_total_amount">
      <span>
        <p>$<%= group.transfers.sum(:amount) %></p>
      </span>
    </div>
  <% end %>
  
  </div>
</section>

    <button class='category'><%= link_to "New category", new_group_path %></button>
  

</div>

app/views/groups/new.html.erb
<%= render 'shared/navbar' %>
<button class="back"><%= link_to "back", groups_path  %></button>
<div class="group_main_div">
<h2 class="group_main_title">New Category</h2>
<div >
    <%= form_with(model: @group, url: groups_path, method: :post) do |f| %>
  <div class="group_form">
      <div>
        <%= f.label :name %>
        <%= f.text_field :name, placeholder: "Name", autocomplete: "name", class: 'field' %>
    </div>

    <div>
      <%= f.label :icon, class: "label" %>
      <%= f.text_field :icon, placeholder: "Icon URL", autocomplete: "name", class: 'field' %>
    </div>
 
    <div><%= f.submit 'save', class: 'category' %></div>
     </div>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
    <div class="Home_container">
    
        <h1 class="tracker">Expense Tracker</h1>
        <h3 class="welcome">Welcome</h3>
    
        <div class="home_button">
            <button class="button"><%= link_to 'Signup', new_user_registration_path%></button>
            <button class="button"><%= link_to 'Sign in',  new_user_session_path%></button>
        </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_links.html.erb
<div class="log-link">
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="nav-group">
<p class="user-info"> <%= current_user.full_name %> </p>
<div class="links">
    <%= link_to "Transaction", groups_path, class: "btn" %>
    <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"btn1" %>
</div>
</div>

app/views/transfers/index.html.erb
<%= render 'shared/navbar', group: @groups %>
<button class="back"><%= link_to "back", groups_path  %></button>


<div class="group_main_div">
  <h3 class="group_main_title">Expenses</h3>
  <% if @transfers.empty? %>
    <h3 class="group_main_title">You do not have any transfers yet</h3>
  <% else %>
    <div>
      <div class="transact_div">
      <h1><%= @group.name %></h1>
      <span>$<%= @transfers.sum(:amount) %></span>
      </div>
      
        <% @transfers.each do |transfer| %>
        <div class="transact_subdiv">
              <h2 class="name"><%= transfer.name %></h2>
              <p class= "dollar">$<%= transfer.amount %></p>
      </div>
         
        <% end %>
    
    </div>
  <% end %>
  
   <button class='category' ><%= link_to 'Add new transaction', new_group_transfer_path %></button>
</div>

app/views/transfers/new.html.erb
<%= render 'shared/navbar' %>

<button class="back"><%= link_to "back", groups_path  %></button>

<div class="group_main_div">
  <h2 class="group_main_title">Add New Expense</h2>

  <%= form_with(model: @transfer, url: group_transfers_path, method: :post) do |f| %>
  <div  class="group_form">
    <div>
      <%= f.label :name %>
      <%= f.text_field :name, placeholder: 'Name Expenses', class: "field" %>
    </div>

    <div class="field">
      <%= f.label :amount %>
      <%= f.number_field :amount, step: 1, placeholder: 'Amount Spent', class: "field"%>
    </div>

    <% if @groups.present? %>
      <div>
        <%= f.label :groups %>
        <% @groups.each do |group| %>
          <div class="checkbox">
            <%= f.check_box :group_ids, { multiple: true }, group.id %>
            <%= f.label group.name %>
          </div>
        <% end %>
      </div>
    <% end %>
  
    <%= f.submit 'Save', class: 'category' %>
    </div>
  <% end %>
</div>